/*
 * Created by andii on 15/11/21 12.51
 * Copyright (c) 2021 . All rights reserved.
 * Last modified 15/11/21 12.08
 */

// Mocks generated by Mockito 5.0.16 from annotations
// in laporhoax/test/presentation/provider/register_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:laporhoax/data/models/register.dart' as _i8;
import 'package:laporhoax/domain/entities/register_data.dart' as _i7;
import 'package:laporhoax/domain/repositories/repository.dart' as _i2;
import 'package:laporhoax/domain/usecases/post_fcm_token.dart' as _i9;
import 'package:laporhoax/domain/usecases/post_register.dart' as _i4;
import 'package:laporhoax/utils/failure.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeRepository_0 extends _i1.Fake implements _i2.Repository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [PostRegister].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRegister extends _i1.Mock implements _i4.PostRegister {
  MockPostRegister() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepository_0()) as _i2.Repository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.RegisterData>> execute(
          _i8.Register? user) =>
      (super.noSuchMethod(Invocation.method(#execute, [user]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.RegisterData>>.value(
              _FakeEither_1<_i6.Failure, _i7.RegisterData>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.RegisterData>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PostFCMToken].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostFCMToken extends _i1.Mock implements _i9.PostFCMToken {
  MockPostFCMToken() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepository_0()) as _i2.Repository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          int? user, String? fcmToken) =>
      (super.noSuchMethod(Invocation.method(#execute, [user, fcmToken]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}
