name: core
description: Core Flutter.
version: 0.0.1
homepage: https://ti.pnp.ac.id

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^9.0.0
  font_awesome_flutter: ^9.1.0
  flutter_signin_button: ^2.0.0
  pull_to_refresh: ^2.0.0
  dio: ^4.0.0
  intl: ^0.17.0
  webview_flutter: ^2.1.1
  path_provider: ^2.0.5
  image_picker: ^0.8.4
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  share: ^2.0.4
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.12
  sqflite: ^2.0.0+3
  provider: ^6.0.1
  flutter_progress_hud: ^2.0.0
  shared_preferences: ^2.0.5
  rxdart: ^0.27.2
  image_cropper: ^1.4.1
  http_mock_adapter: ^0.3.2
  package_info_plus: ^1.3.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  cached_network_image: ^3.0.0
  flutter_slidable: ^0.6.0
  firebase_messaging: ^10.0.8
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.16
  build_runner: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
