// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/provider/report_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:core/data/models/report_request.dart' as _i9;
import 'package:core/domain/entities/category.dart' as _i12;
import 'package:core/domain/entities/report.dart' as _i7;
import 'package:core/domain/repositories/repository.dart' as _i2;
import 'package:core/domain/usecases/delete_report.dart' as _i10;
import 'package:core/domain/usecases/get_categories.dart' as _i11;
import 'package:core/domain/usecases/get_reports.dart' as _i4;
import 'package:core/domain/usecases/post_report.dart' as _i8;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeRepository_0 extends _i1.Fake implements _i2.Repository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetReports].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetReports extends _i1.Mock implements _i4.GetReports {
  MockGetReports() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepository_0()) as _i2.Repository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Report>>> execute(
          String? token, int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [token, id]),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i7.Report>>>.value(
              _FakeEither_1<_i6.Failure, List<_i7.Report>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.Report>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PostReport].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostReport extends _i1.Mock implements _i8.PostReport {
  MockPostReport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepository_0()) as _i2.Repository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Report>> execute(
          String? token, _i9.ReportRequest? report) =>
      (super.noSuchMethod(Invocation.method(#execute, [token, report]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Report>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Report>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Report>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DeleteReport].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteReport extends _i1.Mock implements _i10.DeleteReport {
  MockDeleteReport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepository_0()) as _i2.Repository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(String? token, int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [token, id]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategories extends _i1.Mock implements _i11.GetCategories {
  MockGetCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepository_0()) as _i2.Repository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i12.Category>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i12.Category>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i12.Category>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i12.Category>>>);
  @override
  String toString() => super.toString();
}
