name: flutterTestOnly

on:
  push:
    branches:
      - dev-1
      - ulil

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.10'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install pub Depedencies
        run: flutter pub get
      - name: Run Test
        run: flutter test
        