on: push

jobs:
  assembleRelease:
    name: restoreReleaseKeystore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch private-keystore.jks.asc > android/app/private-keystore.jks
